name: omra
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Versioning information
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons for iOS-style icons
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^4.0.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/sss.png"
  adaptive_icon_foreground: "assets/images/sss.png"
  adaptive_icon_background: "#A29292FF"
  android_round_icon: true  # ← أضيفي هذا السطر


flutter:
  uses-material-design: true

  assets:
    - assets/images/omra.png
